###################
# BUILD FOR LOCAL DEVELOPMENT
###################
FROM node:20-alpine3.20 As development
WORKDIR /usr/src/app
COPY --chown=node:node package*.json ./
RUN npm ci --legacy-peer-deps
COPY --chown=node:node . .
COPY --chown=node:node config.json ./
USER node

###################
# BUILD FOR PRODUCTION
###################
FROM node:20-alpine3.20 As build
WORKDIR /usr/src/app
COPY --chown=node:node package*.json ./
COPY --chown=node:node --from=development /usr/src/app/node_modules ./node_modules
COPY --chown=node:node . .
COPY --chown=node:node config.json ./
RUN npm run build
ENV NODE_ENV production
RUN npm ci --only=production --legacy-peer-deps && npm cache clean --force
USER node

###################
# PRODUCTION
###################
FROM node:20-alpine3.20 As production
WORKDIR /usr/src/app
COPY --chown=node:node --from=build /usr/src/app/node_modules ./node_modules
COPY --chown=node:node --from=build /usr/src/app/dist ./dist
COPY --chown=node:node --from=build /usr/src/app/config.json ./
CMD ["node", "dist/main.js"]